version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/asuntoanalyysi
    depends_on:
      - db
    restart: unless-stopped
    command: >
      bash -c "pip install python-dotenv &&
               flask run --host=0.0.0.0"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=asuntoanalyysi
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: 